import 'package:flutter/material.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedGroup67Widget3.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedGroup45Widget2.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedBookaBusWidget1.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedWhoismakingpaymentWidget2.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedGroup42Widget4.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedDeliverydetailsWidget4.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedBxbxarrowbackWidget12.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedGroup41Widget4.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedWhoismakingpaymentWidget3.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedStatusBarWidget15.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedGroup43Widget3.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedGroup44Widget3.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedNameofReceiverWidget2.dart';
import '/truckportapp/generatedbussection5widget/generated/GeneratedNameofCompanyWidget1.dart';

/* Frame Bus Section 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBusSection5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.009852216748768473,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStatusBarWidget15(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.35733333333333334;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.583743842364532,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNameofReceiverWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup41Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.43466666666666665;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.6908866995073891,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNameofCompanyWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup42Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.536;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.8004926108374384,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWhoismakingpaymentWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 675.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup43Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.536;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.9100985221674877,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWhoismakingpaymentWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup44Widget3(),
              ),
              Positioned(
                left: 143.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 20.0,
                child: GeneratedBookaBusWidget1(),
              ),
              Positioned(
                left: 125.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 20.0,
                child: GeneratedDeliverydetailsWidget4(),
              ),
              Positioned(
                left: 21.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 284.0,
                child: GeneratedGroup67Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 100.0,
                child: GeneratedGroup45Widget2(),
              )
            ]),
      ),
    ));
  }
}
