import 'package:flutter/material.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedtrucksection7widget/generated/GeneratedGroup45Widget6.dart';
import '/truckportapp/generatedtrucksection7widget/generated/GeneratedBxbxarrowbackWidget16.dart';
import '/truckportapp/generatedtrucksection7widget/generated/GeneratedGroup53Widget3.dart';
import '/truckportapp/generatedtrucksection7widget/generated/GeneratedStatusBarWidget19.dart';
import '/truckportapp/generatedtrucksection7widget/generated/GeneratedBookadeliverymanWidget5.dart';

/* Frame Truck Section 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTruckSection7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.009852216748768473,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStatusBarWidget19(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget16(),
              ),
              Positioned(
                left: 0.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 702.0,
                child: GeneratedGroup53Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 418.0,
                child: GeneratedGroup45Widget6(),
              ),
              Positioned(
                left: 104.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 20.0,
                child: GeneratedBookadeliverymanWidget5(),
              )
            ]),
      ),
    ));
  }
}
