import 'package:flutter/material.dart';
import '/truckportapp/generatedfreepikfloorinject7widget/generated/GeneratedVectorWidget2520.dart';
import '/helpers/transform/transform.dart';

/* Group freepik--Floor--inject-7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFreepikFloorinject7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 435.2037658691406,
      height: 227.3562469482422,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 1.0;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 435.2037658691406;

                double percentHeight = 1.0;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 227.3562469482422;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: 0,
                      translateY: 0,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget2520())
                ]);
              }),
            )
          ]),
    ));
  }
}
