import 'package:flutter/material.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedbiker5widget/generated/GeneratedBookadeliverymanWidget4.dart';
import '/truckportapp/generatedbiker5widget/generated/GeneratedGroup53Widget.dart';
import '/truckportapp/generatedbiker5widget/generated/GeneratedStatusBarWidget16.dart';
import '/truckportapp/generatedbiker5widget/generated/GeneratedGroup45Widget3.dart';
import '/truckportapp/generatedbiker5widget/generated/GeneratedBxbxarrowbackWidget13.dart';

/* Frame Biker 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBiker5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: FittedBox(
      fit: BoxFit.fill,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 3.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 702.0,
                child: GeneratedGroup53Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget13(),
              ),
              Positioned(
                left: 0.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 404.0,
                child: GeneratedGroup45Widget3(),
              ),
              Positioned(
                left: 104.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 20.0,
                child: GeneratedBookadeliverymanWidget4(),
              )
            ]),
      ),
    ));
  }
}
