import 'package:flutter/material.dart';
import '/truckportapp/generatedfreepiktextsinject14widget1/generated/GeneratedVectorWidget433.dart';
import '/truckportapp/generatedfreepiktextsinject14widget1/generated/GeneratedVectorWidget431.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedfreepiktextsinject14widget1/generated/GeneratedVectorWidget434.dart';
import '/truckportapp/generatedfreepiktextsinject14widget1/generated/GeneratedCODEWidget1.dart';
import '/truckportapp/generatedfreepiktextsinject14widget1/generated/GeneratedCITYWidget1.dart';
import '/truckportapp/generatedfreepiktextsinject14widget1/generated/GeneratedVectorWidget432.dart';
import '/truckportapp/generatedfreepiktextsinject14widget1/generated/GeneratedADDRESSWidget1.dart';
import '/truckportapp/generatedfreepiktextsinject14widget1/generated/GeneratedCOUNTRYWidget1.dart';

/* Group freepik--Texts--inject-14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFreepikTextsinject14Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 37.56315612792969,
      height: 15.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0116295838023446;

                final double height =
                    constraints.maxHeight * 0.5333333333333333;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedADDRESSWidget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.6921676099700252;

                final double height =
                    constraints.maxHeight * 0.3333333333333333;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.21297464922154624,
                      y: constraints.maxHeight * 0.8,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedCODEWidget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.851898596886185;

                final double height =
                    constraints.maxHeight * 0.5333333333333333;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.26666666666666666,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedCITYWidget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.5482551155910517;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 20.594192504882812;

                double percentHeight = 0.016778564453125;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 0.251678466796875;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.4042004452949724,
                      translateY: constraints.maxHeight * 0.06176350911458333,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget431())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.4529062585432493;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 17.012588500976562;

                double percentHeight = 0.016778564453125;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 0.251678466796875;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.24275237951708123,
                      translateY: constraints.maxHeight * 0.33667449951171874,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget432())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9850077526496513;

                final double height =
                    constraints.maxHeight * 0.5333333333333333;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.5333333333333333,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedCOUNTRYWidget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.33668394577979227;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 12.64691162109375;

                double percentHeight = 0.016779073079427085;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    0.25168609619140625;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.4042004452949724,
                      translateY: constraints.maxHeight * 0.6225575764973958,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget433())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.517717759681266;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 19.447113037109375;

                double percentHeight = 0.016778564453125;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 0.251678466796875;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.482282240318734,
                      translateY: constraints.maxHeight * 0.9532913208007813,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget434())
                ]);
              }),
            )
          ]),
    ));
  }
}
