description: "A new Flutter application."
name: "truckport"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  sizer: ^2.0.15
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Rubik"
      fonts: 
        - 
          asset: "fonts/Rubik-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Rubik-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Rubik-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Rubik-regular.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Rubik-300.ttf"
          style: "normal"
          weight: 300
    - 
      family: "Sora"
      fonts: 
        - 
          asset: "fonts/Sora-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Sora-600.ttf"
          style: "normal"
          weight: 600
    - 
      family: "Montserrat"
      fonts: 
        - 
          asset: "fonts/Montserrat-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Montserrat-800.ttf"
          style: "normal"
          weight: 800
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Poppins"
      fonts: 
        - 
          asset: "fonts/Poppins-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Poppins-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Poppins-300.ttf"
          style: "normal"
          weight: 300
        - 
          asset: "fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true
