import 'package:flutter/material.dart';

/* Rectangle Rectangle
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangleWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1027.0,
      height: 1974.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/c5b48389c4247cbbe5d3805d11c01f2b1b7b97fa.png",
          color: null,
          fit: BoxFit.cover,
          width: 1027.0,
          height: 1974.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
