import 'package:flutter/material.dart';
import '/truckportapp/generatedtracker3widget/generated/GeneratedGroup10Widget2.dart';
import '/truckportapp/generatedtracker3widget/generated/GeneratedBookaDeliveryTruckWidget.dart';
import '/truckportapp/generatedtracker3widget/generated/GeneratedGroup53Widget4.dart';
import '/truckportapp/generatedtracker3widget/generated/GeneratedStatusBarWidget20.dart';
import '/truckportapp/generatedtracker3widget/generated/GeneratedBxbxarrowbackWidget17.dart';
import '/truckportapp/generatedtracker3widget/generated/GeneratedGroup45Widget7.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedtracker3widget/generated/GeneratedRectangle19Widget.dart';

/* Frame Tracker 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTracker3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.009852216748768473,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStatusBarWidget20(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget17(),
              ),
              Positioned(
                left: 0.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 702.0,
                child: GeneratedGroup53Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 418.0,
                child: GeneratedGroup45Widget7(),
              ),
              Positioned(
                left: 104.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 20.0,
                child: GeneratedBookaDeliveryTruckWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedGroup10Widget2(),
              ),
              Positioned(
                left: 151.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 5.0,
                child: GeneratedRectangle19Widget(),
              )
            ]),
      ),
    ));
  }
}
