import 'package:flutter/material.dart';
import '/truckportapp/generatedtrackerwidget/generated/GeneratedGroup4Widget4.dart';
import '/truckportapp/generatedtrackerwidget/generated/GeneratedRectangle6Widget4.dart';
import '/truckportapp/generatedtrackerwidget/generated/GeneratedGroup62Widget1.dart';
import '/truckportapp/generatedtrackerwidget/generated/GeneratedQRTrackerWidget2.dart';
import '/truckportapp/generatedtrackerwidget/generated/GeneratedSearchfortruckvanWidget1.dart';
import '/truckportapp/generatedtrackerwidget/generated/GeneratedGroup61Widget1.dart';
import '/truckportapp/generatedtrackerwidget/generated/GeneratedBxbxarrowbackWidget4.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedtrackerwidget/generated/GeneratedGroup60Widget1.dart';
import '/truckportapp/generatedtrackerwidget/generated/GeneratedOnGoingtripsWidget.dart';
import '/truckportapp/generatedtrackerwidget/generated/GeneratedMaskGroupWidget8.dart';

/* Frame Tracker
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTrackerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054726370449723866;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup4Widget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget4(),
              ),
              Positioned(
                left: 149.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 20.0,
                child: GeneratedQRTrackerWidget2(),
              ),
              Positioned(
                left: 131.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 20.0,
                child: GeneratedOnGoingtripsWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 242.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 93.0,
                child: GeneratedGroup60Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 93.0,
                child: GeneratedGroup61Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 93.0,
                child: GeneratedGroup62Widget1(),
              ),
              Positioned(
                left: 24.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedRectangle6Widget4(),
              ),
              Positioned(
                left: 110.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 18.0,
                child: GeneratedSearchfortruckvanWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 73.0,
                child: GeneratedMaskGroupWidget8(),
              )
            ]),
      ),
    ));
  }
}
