import 'package:flutter/material.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedDeliveryaddresspana1Widget1.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedBookadeliverymanWidget1.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedGroup7Widget1.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedGroup6Widget1.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedEnterAddressWidget1.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedBeerandBarnGRAPortharcourtWidget1.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedFirstBankNigeriaGRAPHWidget.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedGroup38Widget4.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedAddanotherstopWidget1.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedRectangle7Widget3.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedLine1Widget1.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedRectangle6Widget6.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedGroup4Widget7.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedGroup3Widget5.dart';
import '/truckportapp/generatedriker2widget/generated/GeneratedBxbxarrowbackWidget7.dart';

/* Frame Riker 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRiker2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: FittedBox(
      fit: BoxFit.fill,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 24.0,
                  top: 64.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedBxbxarrowbackWidget7(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.08920633951822916;

                    final double height =
                        constraints.maxHeight * 0.02883831033565728;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.456,
                          y: constraints.maxHeight * 0.12561576354679804,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroup3Widget5(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 45.0,
                  top: 618.0,
                  right: null,
                  bottom: null,
                  width: 306.0,
                  height: 50.0,
                  child: GeneratedRectangle6Widget6(),
                ),
                Positioned(
                  left: 88.0,
                  top: 633.0,
                  right: null,
                  bottom: null,
                  width: 197.0,
                  height: 18.0,
                  child: GeneratedFirstBankNigeriaGRAPHWidget(),
                ),
                Positioned(
                  left: 45.0,
                  top: 556.0,
                  right: null,
                  bottom: null,
                  width: 306.0,
                  height: 50.0,
                  child: GeneratedRectangle7Widget3(),
                ),
                Positioned(
                  left: 70.0,
                  top: 571.0,
                  right: null,
                  bottom: null,
                  width: 244.0,
                  height: 18.0,
                  child: GeneratedBeerandBarnGRAPortharcourtWidget1(),
                ),
                Positioned(
                  left: 23.0,
                  top: 728.0,
                  right: null,
                  bottom: null,
                  width: 330.0,
                  height: 48.0,
                  child: GestureDetector(
                    onTap: () {
                      Navigator.of(context).pushNamed('biker2');
                    },
                    child: GeneratedGroup38Widget4(),
                  ),
                ),
                Positioned(
                  left: 104.0,
                  top: 67.0,
                  right: null,
                  bottom: null,
                  width: 169.0,
                  height: 20.0,
                  child: GeneratedBookadeliverymanWidget1(),
                ),
                Positioned(
                  left: 129.0,
                  top: 509.0,
                  right: null,
                  bottom: null,
                  width: 119.0,
                  height: 20.0,
                  child: GeneratedEnterAddressWidget1(),
                ),
                Positioned(
                  left: 136.0,
                  top: 680.0,
                  right: null,
                  bottom: null,
                  width: 101.0,
                  height: 14.0,
                  child: GeneratedAddanotherstopWidget1(),
                ),
                Positioned(
                  left: 24.0,
                  top: 564.0,
                  right: null,
                  bottom: null,
                  width: 11.0,
                  height: 11.0,
                  child: GeneratedGroup7Widget1(),
                ),
                Positioned(
                  left: 24.0,
                  top: 638.0,
                  right: null,
                  bottom: null,
                  width: 11.0,
                  height: 11.0,
                  child: GeneratedGroup6Widget1(),
                ),
                Positioned(
                  left: 29.0,
                  top: 576.0,
                  right: null,
                  bottom: null,
                  width: 68.0,
                  height: 1.0,
                  child: GeneratedLine1Widget1(),
                ),
                Positioned(
                  left: 67.0,
                  top: 164.0,
                  right: null,
                  bottom: null,
                  width: 242.0,
                  height: 242.0,
                  child: GeneratedDeliveryaddresspana1Widget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
