import 'package:flutter/material.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedhomewidget/generated/GeneratedVectorWidget33.dart';
import '/truckportapp/generatedhomewidget/generated/GeneratedRectangle5Widget2.dart';
import '/truckportapp/generatedhomewidget/generated/GeneratedGroup3Widget2.dart';
import '/truckportapp/generatedhomewidget/generated/GeneratedGroup4Widget2.dart';
import '/truckportapp/generatedhomewidget/generated/GeneratedHelloAyodejiOmotayoWidget.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup4Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04800000508626302;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      18.000001907348633;

                  double percentHeight = 0.0246305442208727;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      20.000001907348633;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.904,
                        translateY: constraints.maxHeight * 0.0812807881773399,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget33())
                  ]);
                }),
              ),
              Positioned(
                left: 14.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 25.0,
                child: GeneratedHelloAyodejiOmotayoWidget(),
              ),
              Positioned(
                left: 8.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 73.0,
                child: GeneratedRectangle5Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7573333333333333;

                  final double height =
                      constraints.maxHeight * 0.03201970443349754;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12266666666666666,
                        y: constraints.maxHeight * 0.9285714285714286,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup3Widget2(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
