import 'package:flutter/material.dart';
import '/truckportapp/generatedflashscreenwidget11/generated/GeneratedDownloader2Widget2.dart';
import '/truckportapp/generatedflashscreenwidget11/generated/GeneratedDownloader1Widget4.dart';
import '/truckportapp/generatedflashscreenwidget11/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitTincidun5.dart';
import '/truckportapp/generatedflashscreenwidget11/generated/GeneratedGroup20Widget2.dart';
import '/truckportapp/generatedflashscreenwidget11/generated/GeneratedLetsgetstartedWidget5.dart';
import '/truckportapp/generatedflashscreenwidget11/generated/GeneratedGroup21Widget6.dart';
import '/truckportapp/generatedflashscreenwidget11/generated/GeneratedRectangle4Widget4.dart';

/* Frame Flash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFlashScreenWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -190.0,
                top: -17.0,
                right: null,
                bottom: null,
                width: 664.0,
                height: 727.0,
                child: GeneratedDownloader1Widget4(),
              ),
              Positioned(
                left: -137.0,
                top: -87.0,
                right: null,
                bottom: null,
                width: 1024.0,
                height: 804.0,
                child: GeneratedDownloader2Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle4Widget4(),
              ),
              Positioned(
                left: 23.0,
                top: 681.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 48.0,
                child: GeneratedGroup20Widget2(),
              ),
              Positioned(
                left: 23.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 48.0,
                child: GeneratedGroup21Widget6(),
              ),
              Positioned(
                left: 23.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 77.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitTincidun5(),
              ),
              Positioned(
                left: 23.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 35.0,
                child: GeneratedLetsgetstartedWidget5(),
              )
            ]),
      ),
    ));
  }
}
