import 'package:flutter/material.dart';
import '/truckportapp/generatedbussection4widget/generated/GeneratedBookaBusWidget.dart';
import '/truckportapp/generatedbussection4widget/generated/GeneratedGroup65Widget1.dart';
import '/truckportapp/generatedbussection4widget/generated/GeneratedBxbxarrowbackWidget9.dart';
import '/truckportapp/generatedbussection4widget/generated/GeneratedGroup67Widget1.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedbussection4widget/generated/GeneratedGroup38Widget6.dart';
import '/truckportapp/generatedbussection4widget/generated/GeneratedGroup4Widget9.dart';

/* Frame Bus Section 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBusSection4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 804.0,
                child: GeneratedGroup4Widget9(),
              ),
              Positioned(
                left: 24.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget9(),
              ),
              Positioned(
                left: 23.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 48.0,
                child: GeneratedGroup38Widget6(),
              ),
              Positioned(
                left: 137.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 20.0,
                child: GeneratedBookaBusWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 284.0,
                child: GeneratedGroup67Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6370121256510417;

                  final double height =
                      constraints.maxHeight * 0.1792646699351043;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.17196028645833333,
                        y: constraints.maxHeight * 0.19950738916256158,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup65Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
