import 'package:flutter/material.dart';
import '/truckportapp/generatedflashscreenwidget15/generated/GeneratedGroup61Widget3.dart';
import '/truckportapp/generatedflashscreenwidget15/generated/GeneratedGroup76Widget.dart';
import '/truckportapp/generatedflashscreenwidget15/generated/GeneratedGroup58Widget3.dart';
import '/truckportapp/generatedflashscreenwidget15/generated/GeneratedGroup62Widget3.dart';
import '/truckportapp/generatedflashscreenwidget15/generated/GeneratedLetsKnowYouWidget1.dart';
import '/truckportapp/generatedflashscreenwidget15/generated/GeneratedGroup59Widget17.dart';
import '/truckportapp/generatedflashscreenwidget15/generated/GeneratedGroup60Widget3.dart';
import '/truckportapp/generatedflashscreenwidget15/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitTincidun7.dart';

/* Frame Flash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFlashScreenWidget15 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 23.0,
                top: 732.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 50.0,
                child: GeneratedGroup76Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 77.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitTincidun7(),
              ),
              Positioned(
                left: 23.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 35.0,
                child: GeneratedLetsKnowYouWidget1(),
              ),
              Positioned(
                left: 23.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 75.0,
                child: GeneratedGroup58Widget3(),
              ),
              Positioned(
                left: 23.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 75.0,
                child: GeneratedGroup59Widget17(),
              ),
              Positioned(
                left: 23.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 75.0,
                child: GeneratedGroup62Widget3(),
              ),
              Positioned(
                left: 23.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 75.0,
                child: GeneratedGroup60Widget3(),
              ),
              Positioned(
                left: 23.0,
                top: 625.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 75.0,
                child: GeneratedGroup61Widget3(),
              )
            ]),
      ),
    ));
  }
}
