import 'package:flutter/material.dart';

/* Text Welcome to truckport
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWelcometotruckportWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Welcome to truckport''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 16.0,
        fontFamily: 'Rubik',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 241, 120, 182),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
