import 'package:flutter/material.dart';
import '/truckportapp/generatedflashscreenwidget13/generated/GeneratedBackarrrowWidget1.dart';
import '/truckportapp/generatedflashscreenwidget13/generated/GeneratedEmailVerificationWidget.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedflashscreenwidget13/generated/GeneratedGroup57Widget1.dart';
import '/truckportapp/generatedflashscreenwidget13/generated/GeneratedDidintgetcoderesendcodeWidget1.dart';
import '/truckportapp/generatedflashscreenwidget13/generated/GeneratedGroup21Widget8.dart';
import '/truckportapp/generatedflashscreenwidget13/generated/GeneratedEnter6DigitcodeforphoneVerificationWidget.dart';

/* Frame Flash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFlashScreenWidget13 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 23.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 50.0,
                child: GeneratedGroup21Widget8(),
              ),
              Positioned(
                left: 28.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 27.0,
                child: GeneratedEnter6DigitcodeforphoneVerificationWidget(),
              ),
              Positioned(
                left: 93.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 195.0,
                height: 21.0,
                child: GeneratedDidintgetcoderesendcodeWidget1(),
              ),
              Positioned(
                left: 23.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 65.0,
                child: GeneratedEmailVerificationWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 50.0,
                child: GeneratedGroup57Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.058666666666666666;

                  final double height =
                      constraints.maxHeight * 0.017241379310344827;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06666666666666667,
                        y: constraints.maxHeight * 0.05665024630541872,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBackarrrowWidget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
