import 'package:flutter/material.dart';

/* Rectangle Rectangle
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 623.0,
      height: 1149.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/9bfad9683c683ff89498ae42760c3e6e25d45bfa.png",
          color: null,
          fit: BoxFit.cover,
          width: 623.0,
          height: 1149.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
