import 'package:flutter/material.dart';
import '/truckportapp/generatedflashscreenwidget14/generated/GeneratedCreateanaccountWidget.dart';
import '/truckportapp/generatedflashscreenwidget14/generated/GeneratedGroup58Widget2.dart';
import '/truckportapp/generatedflashscreenwidget14/generated/GeneratedGroup21Widget9.dart';
import '/truckportapp/generatedflashscreenwidget14/generated/GeneratedIhaveanaccountSigninWidget.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedflashscreenwidget14/generated/GeneratedBackarrrowWidget2.dart';

/* Frame Flash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFlashScreenWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 23.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 50.0,
                child: GeneratedGroup21Widget9(),
              ),
              Positioned(
                left: 98.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 21.0,
                child: GeneratedIhaveanaccountSigninWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 36.0,
                child: GeneratedCreateanaccountWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.058666666666666666;

                  final double height =
                      constraints.maxHeight * 0.017241379310344827;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06666666666666667,
                        y: constraints.maxHeight * 0.05665024630541872,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBackarrrowWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 23.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 75.0,
                child: GeneratedGroup58Widget2(),
              )
            ]),
      ),
    ));
  }
}
