import 'package:flutter/material.dart';
import '/truckportapp/generatedflashscreenwidget16/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitTincidun8.dart';
import '/truckportapp/generatedflashscreenwidget16/generated/GeneratedLetsKnowYouWidget2.dart';
import '/truckportapp/generatedflashscreenwidget16/generated/GeneratedGroup59Widget18.dart';
import '/truckportapp/generatedflashscreenwidget16/generated/GeneratedGroup58Widget4.dart';
import '/truckportapp/generatedflashscreenwidget16/generated/GeneratedGroup61Widget4.dart';
import '/truckportapp/generatedflashscreenwidget16/generated/GeneratedGroup60Widget4.dart';
import '/truckportapp/generatedflashscreenwidget16/generated/GeneratedGroup62Widget4.dart';
import '/truckportapp/generatedflashscreenwidget16/generated/GeneratedGroup75Widget.dart';

/* Frame Flash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFlashScreenWidget16 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 23.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 50.0,
                child: GeneratedGroup75Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 77.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitTincidun8(),
              ),
              Positioned(
                left: 23.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 35.0,
                child: GeneratedLetsKnowYouWidget2(),
              ),
              Positioned(
                left: 28.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 73.0,
                child: GeneratedGroup58Widget4(),
              ),
              Positioned(
                left: 23.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 75.0,
                child: GeneratedGroup59Widget18(),
              ),
              Positioned(
                left: 23.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 75.0,
                child: GeneratedGroup60Widget4(),
              ),
              Positioned(
                left: 23.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 75.0,
                child: GeneratedGroup61Widget4(),
              ),
              Positioned(
                left: 23.0,
                top: 624.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 75.0,
                child: GeneratedGroup62Widget4(),
              )
            ]),
      ),
    ));
  }
}
