import 'package:flutter/material.dart';
import '/truckportapp/generatedflashscreenwidget17/generated/GeneratedGroup63Widget5.dart';
import '/truckportapp/generatedflashscreenwidget17/generated/GeneratedWelcometoTeamCarrozaWidget.dart';
import '/truckportapp/generatedflashscreenwidget17/generated/GeneratedCongratulationsWidget3.dart';

/* Frame Flash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFlashScreenWidget17 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 23.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 50.0,
                child: GeneratedGroup63Widget5(),
              ),
              Positioned(
                left: 92.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 20.0,
                child: GeneratedWelcometoTeamCarrozaWidget(),
              ),
              Positioned(
                left: 85.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 38.0,
                child: GeneratedCongratulationsWidget3(),
              )
            ]),
      ),
    ));
  }
}
