import 'package:flutter/material.dart';
import '/truckportapp/generatedflashscreenwidget10/generated/GeneratedGroup21Widget5.dart';
import '/truckportapp/generatedflashscreenwidget10/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitTincidun4.dart';
import '/truckportapp/generatedflashscreenwidget10/generated/GeneratedRectangle4Widget3.dart';
import '/truckportapp/generatedflashscreenwidget10/generated/GeneratedDownloader1Widget3.dart';
import '/truckportapp/generatedflashscreenwidget10/generated/GeneratedLetsgetstartedWidget4.dart';

/* Frame Flash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFlashScreenWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -190.0,
                top: -17.0,
                right: null,
                bottom: null,
                width: 664.0,
                height: 727.0,
                child: GeneratedDownloader1Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle4Widget3(),
              ),
              Positioned(
                left: 23.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 48.0,
                child: GeneratedGroup21Widget5(),
              ),
              Positioned(
                left: 23.0,
                top: 571.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 77.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitTincidun4(),
              ),
              Positioned(
                left: 23.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 35.0,
                child: GeneratedLetsgetstartedWidget4(),
              )
            ]),
      ),
    ));
  }
}
