import 'package:flutter/material.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedRectangle15Widget16.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedModelYearWidget5.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedImageSnapshotsWidget.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedGroup38Widget3.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedRectangle14Widget13.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedMaskGroupWidget16.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedMaskGroupWidget17.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedSelectVehicleWidget2.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedBxbxarrowbackWidget6.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedCapacityWidget15.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedACWidget.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedYesWidget1.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedMaskGroupWidget18.dart';
import '/truckportapp/generatedbussection2widget/generated/Generated2008Widget1.dart';
import '/truckportapp/generatedbussection2widget/generated/Generated18SeatWidget5.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedNameWidget13.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedGroup4Widget6.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedToyotaHiaceWidget1.dart';
import '/truckportapp/generatedbussection2widget/generated/GeneratedMayatinoWidget1.dart';

/* Frame Bus Section 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBusSection2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054726370449723866;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup4Widget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget6(),
              ),
              Positioned(
                left: 128.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 20.0,
                child: GeneratedSelectVehicleWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 107.0,
                child: GeneratedRectangle14Widget13(),
              ),
              Positioned(
                left: 20.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 45.0,
                child: GeneratedRectangle15Widget16(),
              ),
              Positioned(
                left: 118.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 20.0,
                child: GeneratedImageSnapshotsWidget(),
              ),
              Positioned(
                left: 131.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 18.0,
                child: GeneratedToyotaHiaceWidget1(),
              ),
              Positioned(
                left: 131.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 19.0,
                child: GeneratedModelYearWidget5(),
              ),
              Positioned(
                left: 131.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 22.0,
                child: GeneratedCapacityWidget15(),
              ),
              Positioned(
                left: 131.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 19.0,
                child: GeneratedNameWidget13(),
              ),
              Positioned(
                left: 236.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 19.0,
                child: GeneratedMayatinoWidget1(),
              ),
              Positioned(
                left: 131.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 22.0,
                child: GeneratedACWidget(),
              ),
              Positioned(
                left: 236.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 22.0,
                child: GeneratedYesWidget1(),
              ),
              Positioned(
                left: 236.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 22.0,
                child: Generated2008Widget1(),
              ),
              Positioned(
                left: 236.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 19.0,
                child: Generated18SeatWidget5(),
              ),
              Positioned(
                left: 29.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 78.0,
                child: GeneratedMaskGroupWidget16(),
              ),
              Positioned(
                left: 27.0,
                top: 436.0,
                right: null,
                bottom: null,
                width: 153.3118896484375,
                height: 121.0,
                child: GeneratedMaskGroupWidget17(),
              ),
              Positioned(
                left: 193.6881103515625,
                top: 436.0,
                right: null,
                bottom: null,
                width: 153.3118896484375,
                height: 121.0,
                child: GeneratedMaskGroupWidget18(),
              ),
              Positioned(
                left: 23.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 48.0,
                child: GeneratedGroup38Widget3(),
              )
            ]),
      ),
    ));
  }
}
