import 'package:flutter/material.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedGroup41Widget6.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedNameofCompanyWidget2.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitInmassav2.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedBookadeliverymanWidget10.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedStatusBarWidget31.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedGroup47Widget3.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedUnionWidget20.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedGroup67Widget7.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedRectangle11Widget2.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedReceiverPhonenumberWidget2.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedNowWidget.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedRectangle8Widget59.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedTypeofgoodsWidget1.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedGroup43Widget4.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedRectangle9Widget.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedUploadimageWidget.dart';
import '/truckportapp/generatedtrucksection5widget/generated/Generated12122021Widget3.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedDescribtionofAddressWidget1.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedDocumentWidget2.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedNameofReceiverWidget4.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedRectangle13Widget2.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedTimeScheduleWidget.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedPaymentmethodWidget.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedRectangle10Widget2.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedBxbxarrowbackWidget25.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedRectangle12Widget2.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedDateScheduleWidget.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedDeliverydetailsWidget6.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedNoteWidget3.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitInmassav3.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedGroup42Widget6.dart';
import '/truckportapp/generatedtrucksection5widget/generated/GeneratedImageofgoodsWidget.dart';

/* Frame Truck Section 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTruckSection5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1702.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1702.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height = constraints.maxHeight *
                                    0.025851938895417155;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          0.0005875440658049354,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedStatusBarWidget31(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.064;

                                final double height =
                                    constraints.maxHeight * 0.01410105757931845;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.03760282021151586,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedBxbxarrowbackWidget25(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.35733333333333334;

                                final double height = constraints.maxHeight *
                                    0.010575793184488837;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.2784958871915394,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedNameofReceiverWidget4(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height =
                                    constraints.maxHeight * 0.0282021151586369;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.29318448883666276,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup41Widget6(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.43466666666666665;

                                final double height = constraints.maxHeight *
                                    0.010575793184488837;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.3296122209165687,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedNameofCompanyWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height =
                                    constraints.maxHeight * 0.0282021151586369;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.34430082256169214,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup42Widget6(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.344;

                                final double height = constraints.maxHeight *
                                    0.010575793184488837;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.381903642773208,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedPaymentmethodWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height =
                                    constraints.maxHeight * 0.0282021151586369;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.39659224441833135,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup43Widget4(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.45066666666666666;

                                final double height = constraints.maxHeight *
                                    0.011750881316098707;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.2773333333333333,
                                      y: constraints.maxHeight *
                                          0.03936545240893067,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedBookadeliverymanWidget10(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.33866666666666667;

                                final double height = constraints.maxHeight *
                                    0.011750881316098707;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3333333333333333,
                                      y: constraints.maxHeight *
                                          0.2596944770857814,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedDeliverydetailsWidget6(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height =
                                    constraints.maxHeight * 0.16686251468860164;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.056,
                                      y: constraints.maxHeight *
                                          0.06639247943595769,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup67Widget7(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.536;

                                final double height = constraints.maxHeight *
                                    0.010575793184488837;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.43419506462984725,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedTimeScheduleWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height =
                                    constraints.maxHeight * 0.0282021151586369;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.4488836662749706,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle9Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.536;

                                final double height = constraints.maxHeight *
                                    0.010575793184488837;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.4864864864864865,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedDateScheduleWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.44266666666666665;

                                final double height = constraints.maxHeight *
                                    0.012338425381903642;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.12,
                                      y: constraints.maxHeight *
                                          0.4571092831962397,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedNowWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height =
                                    constraints.maxHeight * 0.0282021151586369;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.5011750881316098,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle12Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.021015579223632813;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        7.880842208862305;

                                double percentHeight = 0.009048192957733549;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        15.4000244140625;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.8506666666666667,
                                      translateY: constraints.maxHeight *
                                          0.4582843713278496,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedUnionWidget20())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.44266666666666665;

                                final double height = constraints.maxHeight *
                                    0.012338425381903642;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.12,
                                      y: constraints.maxHeight *
                                          0.5094007050528789,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated12122021Widget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height =
                                    constraints.maxHeight * 0.0282021151586369;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.6057579318448884,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle10Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.44266666666666665;

                                final double height = constraints.maxHeight *
                                    0.012338425381903642;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.12,
                                      y: constraints.maxHeight *
                                          0.6139835487661575,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedDocumentWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height =
                                    constraints.maxHeight * 0.0282021151586369;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.6580493537015276,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle13Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.43466666666666665;

                                final double height = constraints.maxHeight *
                                    0.010575793184488837;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.12,
                                      y: constraints.maxHeight *
                                          0.6662749706227967,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedUploadimageWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height =
                                    constraints.maxHeight * 0.05464159811985899;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.7103407755581669,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle11Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.7413333333333333;

                                final double height =
                                    constraints.maxHeight * 0.03407755581668625;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.12,
                                      y: constraints.maxHeight *
                                          0.7197414806110458,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedLoremipsumdolorsitametconsecteturadipiscingelitInmassav2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height =
                                    constraints.maxHeight * 0.03290246768507638;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.7890716803760282,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle8Widget59(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.8106666666666666;

                                final double height = constraints.maxHeight *
                                    0.018213866039952998;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.12,
                                      y: constraints.maxHeight *
                                          0.7943595769682726,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedLoremipsumdolorsitametconsecteturadipiscingelitInmassav3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.536;

                                final double height = constraints.maxHeight *
                                    0.010575793184488837;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.5910693301997649,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedTypeofgoodsWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.536;

                                final double height = constraints.maxHeight *
                                    0.010575793184488837;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.6956521739130435,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedDescribtionofAddressWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.544;

                                final double height = constraints.maxHeight *
                                    0.012338425381903642;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.7743830787309048,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedNoteWidget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.536;

                                final double height = constraints.maxHeight *
                                    0.010575793184488837;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.6433607520564042,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedImageofgoodsWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.536;

                                final double height = constraints.maxHeight *
                                    0.010575793184488837;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.5387779083431258,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedReceiverPhonenumberWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.88;

                                final double height =
                                    constraints.maxHeight * 0.0282021151586369;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.5534665099882491,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup47Widget3(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
