import 'package:flutter/material.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedGroup68Widget2.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedGroup67Widget8.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedRectangle12Widget3.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedBookaBusWidget3.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedBxbxarrowbackWidget26.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedAlternativePhonenumberWidget.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedTimeScheduleWidget1.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedDeliverydetailsWidget7.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedGroup41Widget7.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedRectangle8Widget64.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedGroup42Widget7.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedPaymentmethodWidget1.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedReceiverPhonenumberWidget3.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedGroup47Widget4.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedTypeofTripWidget.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedRectangle9Widget1.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedStatusBarWidget32.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedNowWidget1.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedUnionWidget25.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedCategoryofPassengersWidget.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitInmassav4.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedGroup43Widget5.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedDateScheduleWidget1.dart';
import '/truckportapp/generatedbussection6widget/generated/Generated12122021Widget4.dart';
import '/truckportapp/generatedbussection6widget/generated/GeneratedNoteWidget4.dart';

/* Frame Bus Section 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBusSection6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1365.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1365.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 0.03223443223443224;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          0.0007326007326007326,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedStatusBarWidget32(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.064;

                                final double height = constraints.maxHeight *
                                    0.017582417582417582;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.046886446886446886,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedBxbxarrowbackWidget26(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.35733333333333334;

                                final double height = constraints.maxHeight *
                                    0.013186813186813187;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.34725274725274724,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedTypeofTripWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height = constraints.maxHeight *
                                    0.035164835164835165;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.36556776556776555,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup41Widget7(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.5013333333333333;

                                final double height = constraints.maxHeight *
                                    0.013186813186813187;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.41098901098901097,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedCategoryofPassengersWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height = constraints.maxHeight *
                                    0.035164835164835165;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.4293040293040293,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup42Widget7(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.344;

                                final double height = constraints.maxHeight *
                                    0.013186813186813187;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.47619047619047616,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedPaymentmethodWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height = constraints.maxHeight *
                                    0.035164835164835165;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.56,
                                      y: constraints.maxHeight *
                                          0.4945054945054945,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup43Widget5(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.256;

                                final double height = constraints.maxHeight *
                                    0.014652014652014652;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.376,
                                      y: constraints.maxHeight *
                                          0.04908424908424908,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedBookaBusWidget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.33866666666666667;

                                final double height = constraints.maxHeight *
                                    0.014652014652014652;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3333333333333333,
                                      y: constraints.maxHeight *
                                          0.3238095238095238,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedDeliverydetailsWidget7(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height =
                                    constraints.maxHeight * 0.20805860805860807;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.056,
                                      y: constraints.maxHeight *
                                          0.08278388278388278,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup67Widget8(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.536;

                                final double height = constraints.maxHeight *
                                    0.013186813186813187;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.5413919413919414,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedTimeScheduleWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height = constraints.maxHeight *
                                    0.035164835164835165;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.5597069597069597,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle9Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.536;

                                final double height = constraints.maxHeight *
                                    0.013186813186813187;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.6065934065934065,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedDateScheduleWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.44266666666666665;

                                final double height = constraints.maxHeight *
                                    0.015384615384615385;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.12,
                                      y: constraints.maxHeight *
                                          0.5699633699633699,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedNowWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height = constraints.maxHeight *
                                    0.035164835164835165;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.6249084249084249,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle12Widget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.021015579223632813;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        7.880842208862305;

                                double percentHeight = 0.011282069167811356;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        15.4000244140625;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.8506666666666667,
                                      translateY: constraints.maxHeight *
                                          0.5714285714285714,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedUnionWidget25())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.44266666666666665;

                                final double height = constraints.maxHeight *
                                    0.015384615384615385;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.12,
                                      y: constraints.maxHeight *
                                          0.6351648351648351,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated12122021Widget4(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.872;

                                final double height = constraints.maxHeight *
                                    0.041025641025641026;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.8219780219780219,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle8Widget64(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.8106666666666666;

                                final double height =
                                    constraints.maxHeight * 0.02271062271062271;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.12,
                                      y: constraints.maxHeight *
                                          0.8285714285714286,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedLoremipsumdolorsitametconsecteturadipiscingelitInmassav4(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.544;

                                final double height = constraints.maxHeight *
                                    0.015384615384615385;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.8036630036630037,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedNoteWidget4(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.536;

                                final double height = constraints.maxHeight *
                                    0.013186813186813187;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.6717948717948717,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedReceiverPhonenumberWidget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.88;

                                final double height = constraints.maxHeight *
                                    0.035164835164835165;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.6901098901098901,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup47Widget4(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.536;

                                final double height = constraints.maxHeight *
                                    0.013186813186813187;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.736996336996337,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedAlternativePhonenumberWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.88;

                                final double height = constraints.maxHeight *
                                    0.035164835164835165;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.064,
                                      y: constraints.maxHeight *
                                          0.7553113553113553,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup68Widget2(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
