import 'package:flutter/material.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedDeliverydetailsWidget3.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedWhoismakingpaymentWidget1.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedBxbxarrowbackWidget11.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedWhoismakingpaymentWidget.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedGroup41Widget3.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedGroup42Widget3.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedGroup45Widget1.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedGroup44Widget2.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedGroup67Widget2.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedNameofReceiverWidget1.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedNameofCompanyWidget.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedStatusBarWidget14.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedBookadeliverymanWidget3.dart';
import '/truckportapp/generatedtrucksection4widget/generated/GeneratedGroup43Widget2.dart';

/* Frame Truck Section 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTruckSection4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.009852216748768473,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStatusBarWidget14(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.35733333333333334;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.583743842364532,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNameofReceiverWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup41Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.43466666666666665;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.6908866995073891,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNameofCompanyWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup42Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.536;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.8004926108374384,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWhoismakingpaymentWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 675.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup43Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.536;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.9100985221674877,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWhoismakingpaymentWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup44Widget2(),
              ),
              Positioned(
                left: 104.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 20.0,
                child: GeneratedBookadeliverymanWidget3(),
              ),
              Positioned(
                left: 125.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 20.0,
                child: GeneratedDeliverydetailsWidget3(),
              ),
              Positioned(
                left: 21.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 284.0,
                child: GeneratedGroup67Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 100.0,
                child: GeneratedGroup45Widget1(),
              )
            ]),
      ),
    ));
  }
}
