import 'package:flutter/material.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedVectorWidget22.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedRectangle12Widget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedViewlivelocationofyourparcelorgoodsWidget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedRectangle13Widget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedGroup1Widget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitWidget3.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedQRTruckWidget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedRectangle5Widget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedHelloAnilKelvinWidget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedGroup35Widget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedVectorWidget17.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedEasybookingofbusesforyourtripsandconferencesWidget.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedQRTrackerWidget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedVectorWidget25.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedVectorWidget26.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedRectangle10Widget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedQRBikeWidget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedQRBusWidget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedRectangle11Widget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedVectorWidget23.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedGroup4Widget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedVectorWidget24.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedYourlocationWidget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedRectangle7Widget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedRectangle6Widget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedGroup3Widget1.dart';
import '/truckportapp/generateddashboardwidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitWidget4.dart';
import '/helpers/transform/transform.dart';

/* Frame Dashboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 528.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 8.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 73.0,
                child: GeneratedRectangle5Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.057866668701171874;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      21.700000762939453;

                  double percentHeight = 0.02862576545752915;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      23.244121551513672;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.13333333333333333,
                        translateY: constraints.maxHeight * 0.9298029556650246,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget17())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06933333333333333;

                  final double height =
                      constraints.maxHeight * 0.03201970443349754;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8186666666666667,
                        y: constraints.maxHeight * 0.9285714285714286,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup3Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 30.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 153.20000004768372,
                height: 145.20000004768372,
                child: GeneratedRectangle12Widget1(),
              ),
              Positioned(
                left: 194.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 153.20000004768372,
                height: 145.20000004768372,
                child: GeneratedRectangle13Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup4Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 14.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 47.0,
                child: GeneratedHelloAnilKelvinWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.08920633951822916;

                  final double height =
                      constraints.maxHeight * 0.02883831033565728;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.11733333333333333,
                        y: constraints.maxHeight * 0.43349753694581283,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup1Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 30.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 153.20000004768372,
                height: 194.20000004768372,
                child: GeneratedRectangle7Widget1(),
              ),
              Positioned(
                left: 196.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 153.20000004768372,
                height: 194.20000004768372,
                child: GeneratedRectangle11Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07466666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 28.0;

                  double percentHeight = 0.029556650246305417;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 24.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5626666666666666,
                        translateY: constraints.maxHeight * 0.4618226600985222,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget22())
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 46.0,
                child: GeneratedRectangle10Widget1(),
              ),
              Positioned(
                left: 149.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 19.0,
                child: GeneratedYourlocationWidget1(),
              ),
              Positioned(
                left: 211.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 18.0,
                child: GeneratedQRTruckWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 18.0,
                child: GeneratedQRBikeWidget1(),
              ),
              Positioned(
                left: 211.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitWidget3(),
              ),
              Positioned(
                left: 40.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 18.0,
                child: GeneratedQRBusWidget1(),
              ),
              Positioned(
                left: 211.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 18.0,
                child: GeneratedQRTrackerWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 45.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitWidget4(),
              ),
              Positioned(
                left: 40.0,
                top: 611.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child:
                    GeneratedEasybookingofbusesforyourtripsandconferencesWidget(),
              ),
              Positioned(
                left: 211.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child: GeneratedViewlivelocationofyourparcelorgoodsWidget1(),
              ),
              Positioned(
                left: 121.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 13.0,
                child: GeneratedGroup35Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07466666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 28.0;

                  double percentHeight = 0.03078817733990148;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.3546666666666667,
                        translateY: constraints.maxHeight * 0.9298029556650246,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget23())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07466666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 28.0;

                  double percentHeight = 0.0332512315270936;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 27.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5626666666666666,
                        translateY: constraints.maxHeight * 0.6699507389162561,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget24())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.055111104329427084;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      20.666664123535156;

                  double percentHeight = 0.030223726639019444;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      24.54166603088379;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.10666666666666667,
                        translateY: constraints.maxHeight * 0.6657430714574354,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget25())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.029556650246305417;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 24.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5946666666666667,
                        translateY: constraints.maxHeight * 0.9298029556650246,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget26())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
