import 'package:flutter/material.dart';
import '/truckportapp/generatedgroup53widget9/generated/GeneratedGroup18Widget9.dart';
import '/truckportapp/generatedgroup53widget9/generated/GeneratedRouteWidget18.dart';

/* Group Group 53
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup53Widget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              child: GeneratedRouteWidget18(),
            ),
            Positioned(
              left: 16.0,
              top: 47.0,
              right: null,
              bottom: null,
              width: 152.3798828125,
              height: 244.64430236816406,
              child: GeneratedGroup18Widget9(),
            )
          ]),
    ));
  }
}
