import 'package:flutter/material.dart';
import '/truckportapp/generateddeliveryaddresspana1widget2/generated/GeneratedFreepikBuildingsinject14Widget3.dart';
import '/truckportapp/generateddeliveryaddresspana1widget2/generated/GeneratedFreepikspeechbubbleinject14Widget3.dart';
import '/truckportapp/generateddeliveryaddresspana1widget2/generated/GeneratedFreepikFloorinject14Widget3.dart';
import '/truckportapp/generateddeliveryaddresspana1widget2/generated/GeneratedFreepikLocatorinject14Widget3.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generateddeliveryaddresspana1widget2/generated/GeneratedFreepikBirdsinject14Widget3.dart';
import '/truckportapp/generateddeliveryaddresspana1widget2/generated/GeneratedFreepikTextsinject14Widget3.dart';
import '/truckportapp/generateddeliveryaddresspana1widget2/generated/GeneratedFreepikCharacterinject14Widget3.dart';
import '/truckportapp/generateddeliveryaddresspana1widget2/generated/GeneratedFreepikbackgroundcompleteinject14Widget3.dart';

/* Frame Delivery address-pana 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDeliveryaddresspana1Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 110.0,
        height: 110.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8758599714799361;

                  final double height =
                      constraints.maxHeight * 0.821261943470348;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06552056832747026,
                        y: constraints.maxHeight * 0.036998349970037286,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedFreepikbackgroundcompleteinject14Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8664800470525568;

                  final double height =
                      constraints.maxHeight * 0.0010400251908735795;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05676036314530806,
                        y: constraints.maxHeight * 0.9337997436523438,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikFloorinject14Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.33552093505859376;

                  final double height =
                      constraints.maxHeight * 0.17906001697887075;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1616399418223988,
                        y: constraints.maxHeight * 0.08981979543512518,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikBirdsinject14Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5374200994318182;

                  final double height =
                      constraints.maxHeight * 0.6152199485085227;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.43406004472212356,
                        y: constraints.maxHeight * 0.14858013499866832,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikBuildingsinject14Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.19456010298295454;

                  final double height =
                      constraints.maxHeight * 0.16296669353138316;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7054397583007812,
                        y: constraints.maxHeight * 0.22727305672385475,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikspeechbubbleinject14Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.0845855019309304;

                  final double height =
                      constraints.maxHeight * 0.10762873562899503;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7590941689231179,
                        y: constraints.maxHeight * 0.14490821144797586,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikLocatorinject14Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.15522003173828125;

                  final double height =
                      constraints.maxHeight * 0.10082563920454546;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7231400923295455,
                        y: constraints.maxHeight * 0.28099200508811256,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikTextsinject14Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5934521761807529;

                  final double height =
                      constraints.maxHeight * 0.5676530664617365;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.01844052401455966,
                        y: constraints.maxHeight * 0.367746977372603,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikCharacterinject14Widget3(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
