import 'package:flutter/material.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedWalletWidget5.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedGroup78Widget1.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedGroup86Widget1.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedGroup83Widget1.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedUnionWidget30.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedStatusBarWidget39.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedGroup80Widget1.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedCard1Widget1.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedBxbxarrowbackWidget31.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedCashWidget4.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedSortWidget1.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedCashOnlineWidget.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedGroup87Widget.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedTransactionDetailsWidget1.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedGroup85Widget1.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedGroup84Widget1.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedGroup81Widget1.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedGroup79Widget1.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedOnlineWidget.dart';
import '/truckportapp/generatedriker6widget/generated/GeneratedGroup82Widget1.dart';

/* Frame Riker 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRiker6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget31(),
              ),
              Positioned(
                left: 163.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 23.0,
                child: GeneratedWalletWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStatusBarWidget39(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4106666666666667;

                  final double height =
                      constraints.maxHeight * 0.02586206896551724;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.056,
                        y: constraints.maxHeight * 0.3620689655172414,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTransactionDetailsWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8533333333333334;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.056,
                        y: constraints.maxHeight * 0.41748768472906406,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup79Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8533333333333334;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.056,
                        y: constraints.maxHeight * 0.4876847290640394,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup80Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8533333333333334;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.056,
                        y: constraints.maxHeight * 0.5578817733990148,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup81Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8533333333333334;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.056,
                        y: constraints.maxHeight * 0.6280788177339901,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup82Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8533333333333334;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.056,
                        y: constraints.maxHeight * 0.6982758620689655,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup83Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8533333333333334;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.056,
                        y: constraints.maxHeight * 0.7684729064039408,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup84Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8533333333333334;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.056,
                        y: constraints.maxHeight * 0.8386699507389163,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup85Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8533333333333334;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.056,
                        y: constraints.maxHeight * 0.9088669950738916,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup86Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10666666666666667;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.84,
                        y: constraints.maxHeight * 0.3620689655172414,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSortWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 30.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 117.0,
                child: GeneratedCard1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.056;

                  final double height =
                      constraints.maxHeight * 0.012315270935960592;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7626666666666667,
                        y: constraints.maxHeight * 0.3657635467980296,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup78Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 201.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 76.0,
                child: GeneratedUnionWidget30(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.248;

                  final double height =
                      constraints.maxHeight * 0.01847290640394089;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.608,
                        y: constraints.maxHeight * 0.4064039408866995,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCashOnlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.128;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.608,
                        y: constraints.maxHeight * 0.42980295566502463,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCashWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.14133333333333334;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.608,
                        y: constraints.maxHeight * 0.45320197044334976,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedOnlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 208.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedGroup87Widget(),
              )
            ]),
      ),
    ));
  }
}
