import 'package:flutter/material.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedbussection7widget/generated/GeneratedGroup45Widget11.dart';
import '/truckportapp/generatedbussection7widget/generated/GeneratedGroup53Widget8.dart';
import '/truckportapp/generatedbussection7widget/generated/GeneratedBookaBusWidget2.dart';
import '/truckportapp/generatedbussection7widget/generated/GeneratedStatusBarWidget24.dart';
import '/truckportapp/generatedbussection7widget/generated/GeneratedGroup39Widget10.dart';

/* Frame Bus Section 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBusSection7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.009852216748768473,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStatusBarWidget24(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 702.0,
                child: GeneratedGroup53Widget8(),
              ),
              Positioned(
                left: 1.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 327.0,
                child: GeneratedGroup45Widget11(),
              ),
              Positioned(
                left: 140.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 20.0,
                child: GeneratedBookaBusWidget2(),
              ),
              Positioned(
                left: 23.0,
                top: 727.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 48.0,
                child: GeneratedGroup39Widget10(),
              )
            ]),
      ),
    ));
  }
}
