import 'package:flutter/material.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedVectorWidget2558.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedRectangle13Widget3.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedRectangle10Widget3.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedRectangle12Widget4.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedRectangle6Widget15.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedVectorWidget2564.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedTruckWidget.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedBusWidget.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedYourlocationWidget2.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedVectorWidget2566.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedHelloAnilKelvinWidget2.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedEasybookingofbusesforyourtripsandconferencesWidget1.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedVectorWidget2565.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitWidget6.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedVectorWidget2563.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedGroup35Widget2.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedRectangle5Widget22.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedRectangle11Widget3.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitWidget5.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedGroup4Widget10.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedRectangle7Widget18.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedDeliveryWidget.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedTaxiWidget.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedGroup3Widget9.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedGroup1Widget9.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedViewlivelocationofyourparcelorgoodsWidget2.dart';
import '/truckportapp/generateddashboardwidget1/generated/GeneratedVectorWidget2567.dart';

/* Frame Dashboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 528.0,
                child: GeneratedRectangle6Widget15(),
              ),
              Positioned(
                left: 8.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 73.0,
                child: GeneratedRectangle5Widget22(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.057866668701171874;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      21.700000762939453;

                  double percentHeight = 0.02862576545752915;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      23.244121551513672;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.13333333333333333,
                        translateY: constraints.maxHeight * 0.9298029556650246,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2558())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06933333333333333;

                  final double height =
                      constraints.maxHeight * 0.03201970443349754;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8186666666666667,
                        y: constraints.maxHeight * 0.9285714285714286,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup3Widget9(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 30.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 153.20000004768372,
                height: 145.20000004768372,
                child: GeneratedRectangle12Widget4(),
              ),
              Positioned(
                left: 194.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 153.20000004768372,
                height: 145.20000004768372,
                child: GeneratedRectangle13Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup4Widget10(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 14.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 47.0,
                child: GeneratedHelloAnilKelvinWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.08920633951822916;

                  final double height =
                      constraints.maxHeight * 0.02883831033565728;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.11733333333333333,
                        y: constraints.maxHeight * 0.43349753694581283,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup1Widget9(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 30.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 153.20000004768372,
                height: 194.20000004768372,
                child: GeneratedRectangle7Widget18(),
              ),
              Positioned(
                left: 196.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 153.20000004768372,
                height: 194.20000004768372,
                child: GeneratedRectangle11Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07466666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 28.0;

                  double percentHeight = 0.029556650246305417;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 24.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5626666666666666,
                        translateY: constraints.maxHeight * 0.4618226600985222,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2563())
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 46.0,
                child: GeneratedRectangle10Widget3(),
              ),
              Positioned(
                left: 149.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 19.0,
                child: GeneratedYourlocationWidget2(),
              ),
              Positioned(
                left: 211.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 21.0,
                child: GeneratedTaxiWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 21.0,
                child: GeneratedDeliveryWidget(),
              ),
              Positioned(
                left: 211.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitWidget5(),
              ),
              Positioned(
                left: 40.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 21.0,
                child: GeneratedBusWidget(),
              ),
              Positioned(
                left: 211.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 21.0,
                child: GeneratedTruckWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 45.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitWidget6(),
              ),
              Positioned(
                left: 40.0,
                top: 611.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child:
                    GeneratedEasybookingofbusesforyourtripsandconferencesWidget1(),
              ),
              Positioned(
                left: 211.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child: GeneratedViewlivelocationofyourparcelorgoodsWidget2(),
              ),
              Positioned(
                left: 121.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 13.0,
                child: GeneratedGroup35Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07466666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 28.0;

                  double percentHeight = 0.03078817733990148;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.3546666666666667,
                        translateY: constraints.maxHeight * 0.9298029556650246,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2564())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07466666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 28.0;

                  double percentHeight = 0.0332512315270936;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 27.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5626666666666666,
                        translateY: constraints.maxHeight * 0.6699507389162561,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2565())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.055111104329427084;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      20.666664123535156;

                  double percentHeight = 0.030223726639019444;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      24.54166603088379;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.10666666666666667,
                        translateY: constraints.maxHeight * 0.6657430714574354,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2566())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.029556650246305417;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 24.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5946666666666667,
                        translateY: constraints.maxHeight * 0.9298029556650246,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2567())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
