import 'package:flutter/material.dart';
import '/truckportapp/generatedfreepikdeviceinject7widget/generated/GeneratedVectorWidget2522.dart';
import '/truckportapp/generatedfreepikdeviceinject7widget/generated/GeneratedVectorWidget2525.dart';
import '/truckportapp/generatedfreepikdeviceinject7widget/generated/GeneratedVectorWidget2528.dart';
import '/truckportapp/generatedfreepikdeviceinject7widget/generated/GeneratedVectorWidget2527.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedfreepikdeviceinject7widget/generated/GeneratedVectorWidget2523.dart';
import '/truckportapp/generatedfreepikdeviceinject7widget/generated/GeneratedVectorWidget2524.dart';
import '/truckportapp/generatedfreepikdeviceinject7widget/generated/GeneratedVectorWidget2521.dart';
import '/truckportapp/generatedfreepikdeviceinject7widget/generated/GeneratedVectorWidget2526.dart';

/* Group freepik--Device--inject-7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFreepikDeviceinject7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 363.5400085449219,
      height: 222.11585998535156,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.9916789779860262;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 360.5149841308594;

                double percentHeight = 0.936801866646607;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    208.07855224609375;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.0013409887228342649,
                      translateY: 0,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget2521())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.04674863435226203;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 16.994998931884766;

                double percentHeight = 0.04417973034197238;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 9.813018798828125;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.161667231480534,
                      translateY: constraints.maxHeight * 0.7424404831215563,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget2522())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.3240358702835908;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 117.80000305175781;

                double percentHeight = 0.37175790200792286;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 82.57332611083984;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: 0,
                      translateY: constraints.maxHeight * 0.6280637938087814,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget2523())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.6816031323119226;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 247.79000854492188;

                double percentHeight = 0.7096428867072875;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    157.62294006347656;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.31839686768807735,
                      translateY: constraints.maxHeight * 0.2903571132927125,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget2524())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.8631030535289925;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 313.7724914550781;

                double percentHeight = 0.8157234681073892;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    181.18511962890625;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.06563239272027258,
                      translateY: constraints.maxHeight * 0.06042035271322223,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget2525())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.01185110168924537;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 4.308349609375;

                double percentHeight = 0.011197956114019875;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 2.48724365234375;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.8153458234847675,
                      translateY: constraints.maxHeight * 0.15769110680836199,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget2526())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.023683764206425883;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 8.60999584197998;

                double percentHeight = 0.022394194792253814;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    4.9741058349609375;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.82700662053633,
                      translateY: constraints.maxHeight * 0.21032213256062463,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget2527())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.07134136920619126;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 25.935441970825195;

                double percentHeight = 0.0674768369435551;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    14.987675666809082;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.7495111638811703,
                      translateY: constraints.maxHeight * 0.1364418921058751,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget2528())
                ]);
              }),
            )
          ]),
    ));
  }
}
