import 'package:flutter/material.dart';
import '/truckportapp/generatedfreepikspeechbubbleinject14widget1/generated/GeneratedVectorWidget426.dart';
import '/truckportapp/generatedfreepikspeechbubbleinject14widget1/generated/GeneratedVectorWidget427.dart';
import '/helpers/transform/transform.dart';

/* Group freepik--speech-bubble--inject-14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFreepikspeechbubbleinject14Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 46.87055969238281,
      height: 39.23787307739258,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.9951466756779369;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 46.64308166503906;

                double percentHeight = 0.9923523034719224;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 38.93779373168945;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.003200498484719744,
                      translateY: constraints.maxHeight * 0.0030838113224679864,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget426())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 1.0;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 46.87055969238281;

                double percentHeight = 1.0;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 39.23787307739258;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: 0,
                      translateY: 0,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget427())
                ]);
              }),
            )
          ]),
    ));
  }
}
