import 'package:flutter/material.dart';
import '/truckportapp/generatedtrucksection6widget/generated/GeneratedStatusBarWidget23.dart';
import '/truckportapp/generatedtrucksection6widget/generated/GeneratedGroup53Widget7.dart';
import '/truckportapp/generatedtrucksection6widget/generated/GeneratedBookadeliverymanWidget7.dart';
import '/truckportapp/generatedtrucksection6widget/generated/GeneratedGroup39Widget9.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedtrucksection6widget/generated/GeneratedGroup45Widget10.dart';

/* Frame Truck Section 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTruckSection6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.009852216748768473,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStatusBarWidget23(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 702.0,
                child: GeneratedGroup53Widget7(),
              ),
              Positioned(
                left: 1.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 327.0,
                child: GeneratedGroup45Widget10(),
              ),
              Positioned(
                left: 104.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 20.0,
                child: GeneratedBookadeliverymanWidget7(),
              ),
              Positioned(
                left: 23.0,
                top: 727.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 48.0,
                child: GeneratedGroup39Widget9(),
              )
            ]),
      ),
    ));
  }
}
