import 'package:flutter/material.dart';
import '/truckportapp/generatedflashscreenwidget12/generated/GeneratedDownloader2Widget3.dart';
import '/truckportapp/generatedflashscreenwidget12/generated/GeneratedRectangle4Widget5.dart';
import '/truckportapp/generatedflashscreenwidget12/generated/GeneratedLetsgetstartedWidget6.dart';
import '/truckportapp/generatedflashscreenwidget12/generated/GeneratedGroup21Widget7.dart';
import '/truckportapp/generatedflashscreenwidget12/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitTincidun6.dart';
import '/truckportapp/generatedflashscreenwidget12/generated/GeneratedDownloader1Widget5.dart';
import '/truckportapp/generatedflashscreenwidget12/generated/GeneratedGroup20Widget3.dart';

/* Frame Flash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFlashScreenWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -190.0,
                top: -17.0,
                right: null,
                bottom: null,
                width: 664.0,
                height: 727.0,
                child: GeneratedDownloader1Widget5(),
              ),
              Positioned(
                left: -137.0,
                top: -87.0,
                right: null,
                bottom: null,
                width: 1024.0,
                height: 804.0,
                child: GeneratedDownloader2Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle4Widget5(),
              ),
              Positioned(
                left: 23.0,
                top: 681.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 48.0,
                child: GeneratedGroup20Widget3(),
              ),
              Positioned(
                left: 23.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 48.0,
                child: GeneratedGroup21Widget7(),
              ),
              Positioned(
                left: 23.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 77.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitTincidun6(),
              ),
              Positioned(
                left: 23.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 35.0,
                child: GeneratedLetsgetstartedWidget6(),
              )
            ]),
      ),
    ));
  }
}
