import 'package:flutter/material.dart';
import '/truckportapp/generatedtrucksection2widget/generated/GeneratedBxbxarrowbackWidget1.dart';
import '/truckportapp/generatedtrucksection2widget/generated/GeneratedStatusBarWidget4.dart';
import '/truckportapp/generatedtrucksection2widget/generated/GeneratedTrucktypeWidget.dart';
import '/truckportapp/generatedtrucksection2widget/generated/GeneratedDeliverydetailsWidget.dart';
import '/truckportapp/generatedtrucksection2widget/generated/GeneratedGroup44Widget.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedtrucksection2widget/generated/GeneratedGroup42Widget.dart';
import '/truckportapp/generatedtrucksection2widget/generated/GeneratedLocationWidget1.dart';
import '/truckportapp/generatedtrucksection2widget/generated/GeneratedGroup38Widget1.dart';
import '/truckportapp/generatedtrucksection2widget/generated/GeneratedMaximumWeightWidget.dart';
import '/truckportapp/generatedtrucksection2widget/generated/GeneratedLengthofTruckWidget.dart';
import '/truckportapp/generatedtrucksection2widget/generated/GeneratedGroup43Widget.dart';
import '/truckportapp/generatedtrucksection2widget/generated/GeneratedSearchforatruckvanWidget.dart';
import '/truckportapp/generatedtrucksection2widget/generated/GeneratedGroup41Widget.dart';

/* Frame Truck Section 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTruckSection2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStatusBarWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget1(),
              ),
              Positioned(
                left: 23.0,
                top: 728.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 48.0,
                child: GeneratedGroup38Widget1(),
              ),
              Positioned(
                left: 104.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 20.0,
                child: GeneratedSearchforatruckvanWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.43466666666666665;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.25492610837438423,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTrucktypeWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup41Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.43466666666666665;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.3620689655172414,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLengthofTruckWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup42Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.536;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.47167487684729065,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMaximumWeightWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup43Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.544;

                  final double height =
                      constraints.maxHeight * 0.02586206896551724;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.5812807881773399,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLocationWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup44Widget(),
              ),
              Positioned(
                left: 125.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 20.0,
                child: GeneratedDeliverydetailsWidget(),
              )
            ]),
      ),
    ));
  }
}
