import 'package:flutter/material.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedCompletedRidesWidget1.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedVectorWidget2582.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedVectorWidget2583.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedGroup62Widget6.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedEasybookingofbusesforyourtripsandconferencesWidget3.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedViewlivelocationofyourparcelorgoodsWidget4.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedDeliveryWidget2.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedGroup3Widget11.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedVectorWidget2584.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedRectangle14Widget15.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedVectorWidget2581.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedVectorWidget2577.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedWalletWidget1.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedHelloAnilKelvinWidget4.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedRectangle13Widget5.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedRectangle7Widget20.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedVectorWidget2580.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedRectangle5Widget24.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedAvailableRidesWidget2.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedViewallavailableridesyoucanapplyfproroptintogetWidget1.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedBxbxarrowbackWidget28.dart';
import '/truckportapp/generateddashboardwidget3/generated/GeneratedGroup4Widget12.dart';

/* Frame Dashboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 8.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 73.0,
                child: GeneratedRectangle5Widget24(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.057866668701171874;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      21.700000762939453;

                  double percentHeight = 0.02862576545752915;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      23.244121551513672;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.13333333333333333,
                        translateY: constraints.maxHeight * 0.9298029556650246,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2577())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06933333333333333;

                  final double height =
                      constraints.maxHeight * 0.03201970443349754;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8186666666666667,
                        y: constraints.maxHeight * 0.9285714285714286,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup3Widget11(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 198.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 158.20000004768372,
                height: 194.20000004768372,
                child: GeneratedRectangle13Widget5(),
              ),
              Positioned(
                left: 24.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 328.2000000476837,
                height: 194.20000004768372,
                child: GeneratedRectangle14Widget15(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup4Widget12(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 20.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 30.0,
                child: GeneratedHelloAnilKelvinWidget4(),
              ),
              Positioned(
                left: 24.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 158.20000004768372,
                height: 194.20000004768372,
                child: GeneratedRectangle7Widget20(),
              ),
              Positioned(
                left: 24.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 65.0,
                child: GeneratedGroup62Widget6(),
              ),
              Positioned(
                left: 216.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 21.0,
                child: GeneratedWalletWidget1(),
              ),
              Positioned(
                left: 34.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 18.0,
                child: GeneratedCompletedRidesWidget1(),
              ),
              Positioned(
                left: 216.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child: GeneratedViewlivelocationofyourparcelorgoodsWidget4(),
              ),
              Positioned(
                left: 45.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 18.0,
                child: GeneratedAvailableRidesWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07466666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 28.0;

                  double percentHeight = 0.0332512315270936;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 27.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.576,
                        translateY: constraints.maxHeight * 0.6699507389162561,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2580())
                  ]);
                }),
              ),
              Positioned(
                left: 34.0,
                top: 611.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 49.0,
                child:
                    GeneratedEasybookingofbusesforyourtripsandconferencesWidget3(),
              ),
              Positioned(
                left: 45.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 49.0,
                child:
                    GeneratedViewallavailableridesyoucanapplyfproroptintogetWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07466666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 28.0;

                  double percentHeight = 0.03078817733990148;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.3546666666666667,
                        translateY: constraints.maxHeight * 0.9298029556650246,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2581())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07466666666666667;
                  double scaleX = (constraints.maxWidth * percentWidth) / 28.0;

                  double percentHeight = 0.0332512315270936;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 27.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.12,
                        translateY: constraints.maxHeight * 0.4064039408866995,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2582())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.055111104329427084;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      20.666664123535156;

                  double percentHeight = 0.030223726639019444;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      24.54166603088379;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.09066666666666667,
                        translateY: constraints.maxHeight * 0.6657430714574354,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2583())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.058666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 22.0;

                  double percentHeight = 0.029556650246305417;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 24.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5946666666666667,
                        translateY: constraints.maxHeight * 0.9298029556650246,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2584())
                  ]);
                }),
              ),
              Positioned(
                left: 24.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget28(),
              ),
              Positioned(
                left: 152.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 23.0,
                child: GeneratedDeliveryWidget2(),
              )
            ]),
      ),
    ));
  }
}
