import 'package:flutter/material.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedBxbxarrowbackWidget33.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedGroup73Widget1.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedDeliverydetailsWidget8.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedStatusBarWidget41.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedNoteWidget5.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedGroup49Widget1.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedAvailableRidesWidget5.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedGroup3Widget15.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedTypeofgoodsWidget2.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedDescribtionofAddressWidget2.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedGroup50Widget1.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedGroup68Widget5.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedGroup51Widget7.dart';
import '/truckportapp/generatedriker3widget/generated/GeneratedGroup74Widget1.dart';

/* Frame Riker 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRiker3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxbxarrowbackWidget33(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.08920633951822916;

                  final double height =
                      constraints.maxHeight * 0.02883831033565728;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.456,
                        y: constraints.maxHeight * 0.12561576354679804,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup3Widget15(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 127.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 20.0,
                child: GeneratedAvailableRidesWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStatusBarWidget41(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 14.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 360.502197265625,
                height: 283.0,
                child: GeneratedGroup68Widget5(),
              ),
              Positioned(
                left: 311.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedGroup73Widget1(),
              ),
              Positioned(
                left: 311.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedGroup74Widget1(),
              ),
              Positioned(
                left: 112.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 20.0,
                child: GeneratedDeliverydetailsWidget8(),
              ),
              Positioned(
                left: 24.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup49Widget1(),
              ),
              Positioned(
                left: 24.0,
                top: 617.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 93.0,
                child: GeneratedGroup50Widget1(),
              ),
              Positioned(
                left: 24.0,
                top: 751.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 48.0,
                child: GeneratedGroup51Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.536;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.6194581280788177,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTypeofgoodsWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.536;

                  final double height =
                      constraints.maxHeight * 0.022167487684729065;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.729064039408867,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDescribtionofAddressWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.544;

                  final double height =
                      constraints.maxHeight * 0.02586206896551724;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.8940886699507389,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNoteWidget5(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
