import 'package:flutter/material.dart';

/* Text Congratulations
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCongratulationsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Congratulations''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.1340000915527344,
        fontSize: 25.0,
        fontFamily: 'Rubik',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 241, 120, 182),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
