import 'package:flutter/material.dart';
import '/truckportapp/generateddeliveryamico1widget/generated/GeneratedFreepikChronometerinject7Widget.dart';
import '/truckportapp/generateddeliveryamico1widget/generated/GeneratedFreepikPlantsinject7Widget.dart';
import '/truckportapp/generateddeliveryamico1widget/generated/GeneratedFreepikShadowinject7Widget.dart';
import '/truckportapp/generateddeliveryamico1widget/generated/GeneratedVectorWidget2380.dart';
import '/helpers/transform/transform.dart';
import '/truckportapp/generateddeliveryamico1widget/generated/GeneratedFreepikLocatorinject7Widget.dart';
import '/truckportapp/generateddeliveryamico1widget/generated/GeneratedVectorWidget2379.dart';

/* Frame Delivery-amico 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDeliveryamico1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 500.0,
        height: 500.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.783150634765625;

                  final double height =
                      constraints.maxHeight * 0.26200299072265626;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.082010009765625,
                        y: constraints.maxHeight * -0.0180029296875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikPlantsinject7Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2617861022949219;

                  final double height =
                      constraints.maxHeight * 0.15104747009277344;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.322921142578125,
                        y: constraints.maxHeight * 0.105757080078125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikShadowinject7Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.020369672775268556;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      10.184836387634277;

                  double percentHeight = 0.011758008003234864;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      5.879004001617432;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.797013671875,
                        translateY: constraints.maxHeight * -0.336094970703125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2379())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.020369672775268556;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      10.184836387634277;

                  double percentHeight = 0.011757988929748536;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      5.878994464874268;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.83058837890625,
                        translateY: constraints.maxHeight * -0.34691064453125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2380())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.047688095092773435;

                  final double height =
                      constraints.maxHeight * 0.07561463928222656;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8507587890625,
                        y: constraints.maxHeight * -0.42206982421875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikLocatorinject7Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.08251347351074219;

                  final double height =
                      constraints.maxHeight * 0.10286177062988282;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8658427734375,
                        y: constraints.maxHeight * -0.546,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikChronometerinject7Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
